### ISSUE TITLE
Could you please describe how to build locally?

### ISSUE THREAD

**Issue by ha-le2-ts** [mpuig/rentagpt#1]
Hi thanks for this repo!

Could you please guide how to build this locally?

I've tried make start etc., the server started up but only got a smiley face :)

I've tried to brew install vite but couldn't figure out what else

**Comment by ha-le2-ts** [comment]
Also Fly.io same  :( 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/132053377/235736638-debbc079-3ea5-4451-856e-b7c2a303e1d4.png">

**Comment by mpuig** [comment]
Hi, I just updated the README.md file with the instructions to run the repository locally. 

To give you more context, there is a two-steps process that first build the index.html from the javascript project (directory `frontend`), and then the new file is copied into the `src/templates` directory. From here you can run it as expected.
